version: "2"

services:
  caddy:
    restart: always
    image: abiosoft/caddy
    container_name: caddy
    links:
      - "avr-pizza"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./.caddy:/root/.caddy
    environment:
      ACME_AGREE: "true"

  avr-pizza:
    restart: always
    image: noopkat/avr-pizza 
    container_name: avr-pizza 
    ports:
      - "3000:3000"

